import { Router } from "express";
import * as fiscalController from "../controllers/fiscal.controller";

export const fiscalRouter = Router();

fiscalRouter.get("/config", fiscalController.getConfig);
fiscalRouter.put("/config", fiscalController.updateConfig);
fiscalRouter.get("/empresa", fiscalController.getEmpresaFiscal);
fiscalRouter.put("/empresa", fiscalController.updateEmpresaFiscal);
fiscalRouter.get("/provedor/credenciais", fiscalController.listProviderCredentials);
fiscalRouter.post("/provedor/credenciais", fiscalController.upsertProviderCredential);
fiscalRouter.get("/documentos", fiscalController.listDocuments);
fiscalRouter.post("/preflight", fiscalController.preflight);
fiscalRouter.post("/documentos/preparar", fiscalController.prepare);
fiscalRouter.post("/documentos/emitir", fiscalController.emitir);
fiscalRouter.get("/documentos/:id/xml", fiscalController.xml);
fiscalRouter.get("/documentos/:id/danfe", fiscalController.danfe);
fiscalRouter.post("/documentos/:id/cancelar", fiscalController.cancel);
fiscalRouter.get("/contador/resumo", fiscalController.summary);
fiscalRouter.get("/readiness", fiscalController.readiness);
fiscalRouter.get("/eventos", fiscalController.listEventos);
fiscalRouter.get("/transmissoes", fiscalController.listTransmissoes);
fiscalRouter.get("/certificados", fiscalController.listCertificados);
fiscalRouter.post("/certificados", fiscalController.createCertificado);
fiscalRouter.post("/certificados/:id/testar", fiscalController.testCertificado);
fiscalRouter.delete("/certificados/:id", fiscalController.deleteCertificado);
fiscalRouter.get("/sat-mfe/equipamentos", fiscalController.listSatMfeEquipamentos);
fiscalRouter.post("/sat-mfe/equipamentos", fiscalController.createSatMfeEquipamento);
fiscalRouter.post("/sat-mfe/equipamentos/:id/testar", fiscalController.testSatMfeEquipamento);
fiscalRouter.post("/sat-mfe/cupom", fiscalController.createSatMfeCupom);
