import { Router } from "express";
import * as fiscalController from "../controllers/fiscal.controller";
import { requirePermission } from "../middleware/permission.middleware";

export const fiscalRouter = Router();

fiscalRouter.get("/config", requirePermission("fiscal_configurar"), fiscalController.getConfig);
fiscalRouter.put("/config", requirePermission("fiscal_configurar"), fiscalController.updateConfig);
fiscalRouter.get("/empresa", requirePermission("fiscal_configurar"), fiscalController.getEmpresaFiscal);
fiscalRouter.put("/empresa", requirePermission("fiscal_configurar"), fiscalController.updateEmpresaFiscal);
fiscalRouter.get("/documentos", requirePermission("fiscal_consultar"), fiscalController.listDocuments);
fiscalRouter.post("/preflight", requirePermission("fiscal_emitir"), fiscalController.preflight);
fiscalRouter.post("/documentos/preparar", requirePermission("fiscal_emitir"), fiscalController.prepare);
fiscalRouter.post("/documentos/emitir", requirePermission("fiscal_emitir"), fiscalController.emitir);
fiscalRouter.get("/documentos/:id/xml", requirePermission("fiscal_baixar_xml"), fiscalController.xml);
fiscalRouter.get("/documentos/:id/danfe", requirePermission("fiscal_consultar"), fiscalController.danfe);
fiscalRouter.post("/documentos/:id/cancelar", requirePermission("fiscal_cancelar"), fiscalController.cancel);
fiscalRouter.post("/documentos/:id/consultar-status", requirePermission("fiscal_consultar"), fiscalController.consultarStatus);
fiscalRouter.post("/documentos/:id/reenviar", requirePermission("fiscal_emitir"), fiscalController.reenviar);
fiscalRouter.post("/documentos/:id/carta-correcao", requirePermission("fiscal_inutilizar"), fiscalController.cartaCorrecao);
fiscalRouter.post("/inutilizacao", requirePermission("fiscal_inutilizar"), fiscalController.inutilizacao);
fiscalRouter.get("/contador/resumo", requirePermission("fiscal_consultar"), fiscalController.summary);
fiscalRouter.get("/monitoramento", requirePermission("fiscal_consultar"), fiscalController.monitoring);
fiscalRouter.get("/relatorios/excecoes", requirePermission("fiscal_consultar"), fiscalController.exceptionsReport);
fiscalRouter.post("/monitoramento/polling", requirePermission("fiscal_emitir"), fiscalController.processPolling);
fiscalRouter.get("/readiness", requirePermission("fiscal_configurar"), fiscalController.readiness);
fiscalRouter.get("/eventos", requirePermission("fiscal_ver_logs"), fiscalController.listEventos);
fiscalRouter.get("/transmissoes", requirePermission("fiscal_ver_logs"), fiscalController.listTransmissoes);
fiscalRouter.get("/auditoria", requirePermission("fiscal_ver_logs"), fiscalController.listAuditoria);
fiscalRouter.get("/certificados", requirePermission("fiscal_configurar"), fiscalController.listCertificados);
fiscalRouter.post("/certificados", requirePermission("fiscal_configurar"), fiscalController.createCertificado);
fiscalRouter.post("/certificados/:id/testar", requirePermission("fiscal_configurar"), fiscalController.testCertificado);
fiscalRouter.delete("/certificados/:id", requirePermission("fiscal_configurar"), fiscalController.deleteCertificado);
fiscalRouter.get("/sat-mfe/equipamentos", requirePermission("sat_mfe_configurar"), fiscalController.listSatMfeEquipamentos);
fiscalRouter.post("/sat-mfe/equipamentos", requirePermission("sat_mfe_configurar"), fiscalController.createSatMfeEquipamento);
fiscalRouter.post("/sat-mfe/equipamentos/:id/testar", requirePermission("sat_mfe_configurar"), fiscalController.testSatMfeEquipamento);
fiscalRouter.post("/sat-mfe/cupom", requirePermission("sat_mfe_emitir"), fiscalController.createSatMfeCupom);
