CREATE TABLE IF NOT EXISTS `provedores_pagamento` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `codigo` varchar(50) NOT NULL UNIQUE,
  `nome` varchar(120) NOT NULL,
  `tipo` enum('manual','tef','pos_api','pix_gateway','adquirente') NOT NULL,
  `ativo` boolean NOT NULL DEFAULT true,
  `permitePix` boolean NOT NULL DEFAULT false,
  `permiteCartao` boolean NOT NULL DEFAULT false,
  `permiteEnvioValorPdv` boolean NOT NULL DEFAULT false,
  `requerHomologacao` boolean NOT NULL DEFAULT false,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `configuracoes_pagamento_empresa` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `empresaId` int NOT NULL,
  `habilitarPagamentosManuais` boolean NOT NULL DEFAULT true,
  `habilitarTef` boolean NOT NULL DEFAULT false,
  `habilitarPosApi` boolean NOT NULL DEFAULT false,
  `habilitarPixIntegrado` boolean NOT NULL DEFAULT false,
  `modoPadraoCartao` enum('manual','tef','pos_api') NOT NULL DEFAULT 'manual',
  `exigirNsuNoManual` boolean NOT NULL DEFAULT false,
  `permitirVendaOfflineCartaoManual` boolean NOT NULL DEFAULT true,
  `permitirVendaOfflineTef` boolean NOT NULL DEFAULT false,
  `enviarCargaAutomaticaPdv` boolean NOT NULL DEFAULT true,
  `versaoCarga` int NOT NULL DEFAULT 1,
  `ativo` boolean NOT NULL DEFAULT true,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `config_pagamento_empresa_fk` FOREIGN KEY (`empresaId`) REFERENCES `empresas`(`id`)
);

CREATE TABLE IF NOT EXISTS `formas_pagamento_empresa` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `empresaId` int NOT NULL,
  `codigo` varchar(50) NOT NULL,
  `nome` varchar(120) NOT NULL,
  `tipo` enum('dinheiro','debito','credito','pix','voucher','outro') NOT NULL,
  `modoCaptura` enum('manual','tef','pos_api','pix_integrado') NOT NULL DEFAULT 'manual',
  `provedorId` int,
  `adquirenteId` int,
  `permiteTroco` boolean NOT NULL DEFAULT false,
  `permiteParcelamento` boolean NOT NULL DEFAULT false,
  `maxParcelas` int NOT NULL DEFAULT 1,
  `exigirAutorizacao` boolean NOT NULL DEFAULT false,
  `ativo` boolean NOT NULL DEFAULT true,
  `ordem` int NOT NULL DEFAULT 0,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `formas_pagamento_empresa_fk` FOREIGN KEY (`empresaId`) REFERENCES `empresas`(`id`),
  CONSTRAINT `formas_pagamento_provedor_fk` FOREIGN KEY (`provedorId`) REFERENCES `provedores_pagamento`(`id`)
);

CREATE TABLE IF NOT EXISTS `adquirentes_empresa` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `empresaId` int NOT NULL,
  `provedorId` int,
  `nomeExibicao` varchar(120) NOT NULL,
  `cnpjCredenciadora` varchar(18),
  `codigoEstabelecimento` varchar(100),
  `ambiente` enum('homologacao','producao') NOT NULL DEFAULT 'homologacao',
  `ativo` boolean NOT NULL DEFAULT true,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `adquirentes_empresa_fk` FOREIGN KEY (`empresaId`) REFERENCES `empresas`(`id`),
  CONSTRAINT `adquirentes_provedor_fk` FOREIGN KEY (`provedorId`) REFERENCES `provedores_pagamento`(`id`)
);

CREATE TABLE IF NOT EXISTS `taxas_adquirentes` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `empresaId` int NOT NULL,
  `adquirenteEmpresaId` int,
  `modalidade` enum('debito','credito_vista','credito_parcelado','pix') NOT NULL,
  `bandeira` varchar(50),
  `parcelasInicio` int NOT NULL DEFAULT 1,
  `parcelasFim` int NOT NULL DEFAULT 1,
  `taxaPercentual` int NOT NULL DEFAULT 0,
  `taxaFixaCentavos` int NOT NULL DEFAULT 0,
  `prazoRecebimentoDias` int NOT NULL DEFAULT 0,
  `origem` enum('manual','api_provedor','arquivo_importado','ajuste_usuario') NOT NULL DEFAULT 'manual',
  `provedorTaxaId` varchar(120),
  `ultimaConsultaApiEm` timestamp NULL,
  `ultimaConfirmacaoUsuarioEm` timestamp NULL,
  `confirmadaPeloUsuarioId` int,
  `ativo` boolean NOT NULL DEFAULT true,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `taxas_empresa_fk` FOREIGN KEY (`empresaId`) REFERENCES `empresas`(`id`),
  CONSTRAINT `taxas_adquirente_fk` FOREIGN KEY (`adquirenteEmpresaId`) REFERENCES `adquirentes_empresa`(`id`),
  CONSTRAINT `taxas_usuario_fk` FOREIGN KEY (`confirmadaPeloUsuarioId`) REFERENCES `users`(`id`)
);

CREATE TABLE IF NOT EXISTS `historico_taxas_adquirentes` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `empresaId` int NOT NULL,
  `taxaAdquirenteId` int,
  `adquirenteEmpresaId` int,
  `modalidade` varchar(50) NOT NULL,
  `bandeira` varchar(50),
  `parcelasInicio` int DEFAULT 1,
  `parcelasFim` int DEFAULT 1,
  `taxaAnteriorPercentual` int,
  `taxaNovaPercentual` int,
  `taxaFixaAnteriorCentavos` int,
  `taxaFixaNovaCentavos` int,
  `prazoAnteriorDias` int,
  `prazoNovoDias` int,
  `origem` varchar(50) NOT NULL,
  `payloadApi` text,
  `alteradoPorUsuarioId` int,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT `hist_taxas_empresa_fk` FOREIGN KEY (`empresaId`) REFERENCES `empresas`(`id`),
  CONSTRAINT `hist_taxas_taxa_fk` FOREIGN KEY (`taxaAdquirenteId`) REFERENCES `taxas_adquirentes`(`id`),
  CONSTRAINT `hist_taxas_adquirente_fk` FOREIGN KEY (`adquirenteEmpresaId`) REFERENCES `adquirentes_empresa`(`id`),
  CONSTRAINT `hist_taxas_usuario_fk` FOREIGN KEY (`alteradoPorUsuarioId`) REFERENCES `users`(`id`)
);

CREATE TABLE IF NOT EXISTS `terminais_pagamento` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `empresaId` int NOT NULL,
  `pdvId` varchar(50) NOT NULL,
  `nomeTerminal` varchar(120) NOT NULL,
  `tipo` enum('manual','tef','pos_api') NOT NULL DEFAULT 'manual',
  `provedorId` int,
  `adquirenteEmpresaId` int,
  `serialEquipamento` varchar(120),
  `codigoTerminal` varchar(120),
  `ipTerminal` varchar(60),
  `portaTerminal` int,
  `pathIntegradorLocal` varchar(500),
  `estabelecimentoTef` varchar(120),
  `terminalTef` varchar(120),
  `ativo` boolean NOT NULL DEFAULT true,
  `ultimaCargaEnviadaEm` timestamp NULL,
  `ultimoStatus` varchar(80) DEFAULT 'Nao configurado',
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `terminais_empresa_fk` FOREIGN KEY (`empresaId`) REFERENCES `empresas`(`id`),
  CONSTRAINT `terminais_provedor_fk` FOREIGN KEY (`provedorId`) REFERENCES `provedores_pagamento`(`id`),
  CONSTRAINT `terminais_adquirente_fk` FOREIGN KEY (`adquirenteEmpresaId`) REFERENCES `adquirentes_empresa`(`id`)
);

CREATE TABLE IF NOT EXISTS `transacoes_pagamento` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `empresaId` int NOT NULL,
  `vendaId` int,
  `vendaUuid` varchar(36),
  `pdvId` varchar(50),
  `terminalPagamentoId` int,
  `formaPagamentoEmpresaId` int,
  `provedorId` int,
  `adquirenteEmpresaId` int,
  `tipo` enum('dinheiro','debito','credito','pix','voucher','outro') NOT NULL,
  `modoCaptura` enum('manual','tef','pos_api','pix_integrado') NOT NULL DEFAULT 'manual',
  `status` enum('pendente','aprovada','negada','cancelada','estornada','erro','conciliada') NOT NULL DEFAULT 'aprovada',
  `valorBrutoCentavos` int NOT NULL,
  `valorTaxaPrevistaCentavos` int NOT NULL DEFAULT 0,
  `valorLiquidoPrevistoCentavos` int NOT NULL DEFAULT 0,
  `parcelas` int NOT NULL DEFAULT 1,
  `bandeira` varchar(50),
  `nsu` varchar(80),
  `codigoAutorizacao` varchar(80),
  `tid` varchar(120),
  `endToEndIdPix` varchar(120),
  `qrCodePix` text,
  `payloadOriginal` text,
  `erroCodigo` varchar(80),
  `erroMensagem` text,
  `dataTransacao` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `transacoes_empresa_fk` FOREIGN KEY (`empresaId`) REFERENCES `empresas`(`id`),
  CONSTRAINT `transacoes_venda_fk` FOREIGN KEY (`vendaId`) REFERENCES `vendas`(`id`),
  CONSTRAINT `transacoes_terminal_fk` FOREIGN KEY (`terminalPagamentoId`) REFERENCES `terminais_pagamento`(`id`),
  CONSTRAINT `transacoes_forma_fk` FOREIGN KEY (`formaPagamentoEmpresaId`) REFERENCES `formas_pagamento_empresa`(`id`),
  CONSTRAINT `transacoes_provedor_fk` FOREIGN KEY (`provedorId`) REFERENCES `provedores_pagamento`(`id`),
  CONSTRAINT `transacoes_adquirente_fk` FOREIGN KEY (`adquirenteEmpresaId`) REFERENCES `adquirentes_empresa`(`id`)
);

INSERT IGNORE INTO `provedores_pagamento`
(`codigo`, `nome`, `tipo`, `ativo`, `permitePix`, `permiteCartao`, `permiteEnvioValorPdv`, `requerHomologacao`)
VALUES
('manual', 'Manual / Qualquer maquininha', 'manual', true, true, true, false, false),
('mercado_pago', 'Mercado Pago', 'pos_api', true, true, true, false, false),
('stone', 'Stone', 'pos_api', true, true, true, false, false),
('pagbank', 'PagBank / PagSeguro', 'pos_api', true, true, true, false, false),
('itau', 'Itau / Iti', 'pos_api', true, true, true, false, false),
('cielo', 'Cielo', 'pos_api', true, true, true, false, false),
('rede', 'Rede', 'pos_api', true, true, true, false, false),
('getnet', 'Getnet', 'pos_api', true, true, true, false, false),
('sitef', 'SiTef', 'tef', true, false, true, true, true),
('paygo', 'PayGo', 'tef', true, false, true, true, true),
('cappta', 'Cappta', 'tef', true, false, true, true, true),
('elgin_tef', 'Elgin TEF', 'tef', true, false, true, true, true),
('efi', 'Efi / Gerencianet', 'pix_gateway', true, true, false, false, false);
