CREATE TABLE `checkout_assinaturas` (
  `id` int AUTO_INCREMENT NOT NULL,
  `uuid` varchar(36) NOT NULL,
  `planoCodigo` varchar(30) NOT NULL,
  `planoNome` varchar(100) NOT NULL,
  `nomeResponsavel` varchar(255) NOT NULL,
  `email` varchar(320) NOT NULL,
  `telefone` varchar(20),
  `cpfCnpj` varchar(20),
  `valorCentavos` int NOT NULL,
  `status` enum('PENDENTE','APROVADO','REJEITADO','CANCELADO','EXPIRADO','ERRO') NOT NULL DEFAULT 'PENDENTE',
  `mercadoPagoPaymentId` varchar(80),
  `mercadoPagoStatusDetail` varchar(120),
  `qrCodePix` text,
  `qrCodeBase64` text,
  `ticketUrl` text,
  `payloadOriginal` text,
  `aprovadoEm` timestamp,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  `updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `checkout_assinaturas_id` PRIMARY KEY(`id`),
  CONSTRAINT `checkout_assinaturas_uuid_unique` UNIQUE(`uuid`),
  CONSTRAINT `checkout_assinaturas_mercadoPagoPaymentId_unique` UNIQUE(`mercadoPagoPaymentId`)
);
