// src/zod/clientes.schema.ts
import { z } from "zod";

export const createClienteSchema = z.object({
  nome: z.string(),
  razaoSocial: z.string().optional().nullable(),
  nomeFantasia: z.string().optional().nullable(),
  tipoPessoa: z.enum(["FISICA", "JURIDICA", "ESTRANGEIRO"]).default("FISICA"),
  cpfCnpj: z.string().optional(),
  inscricaoEstadual: z.string().optional().nullable(),
  indicadorInscricaoEstadual: z.enum(["1", "2", "9"]).default("9"),
  email: z.string().email().optional().or(z.literal("")),
  telefone: z.string().optional(),
  endereco: z.string().optional(),
  logradouro: z.string().optional().nullable(),
  numero: z.string().optional().nullable(),
  complemento: z.string().optional().nullable(),
  bairro: z.string().optional().nullable(),
  municipio: z.string().optional().nullable(),
  codigoMunicipio: z.string().optional().nullable(),
  uf: z.string().optional().nullable(),
  cep: z.string().optional().nullable(),
  pais: z.string().optional().nullable(),
  foto: z.string().optional(),
});

export const updateClienteSchema = z.object({
  nome: z.string().optional(),
  razaoSocial: z.string().optional().nullable(),
  nomeFantasia: z.string().optional().nullable(),
  tipoPessoa: z.enum(["FISICA", "JURIDICA", "ESTRANGEIRO"]).optional(),
  cpfCnpj: z.string().optional(),
  inscricaoEstadual: z.string().optional().nullable(),
  indicadorInscricaoEstadual: z.enum(["1", "2", "9"]).optional(),
  email: z.string().email().optional().or(z.literal("")),
  telefone: z.string().optional(),
  endereco: z.string().optional(),
  logradouro: z.string().optional().nullable(),
  numero: z.string().optional().nullable(),
  complemento: z.string().optional().nullable(),
  bairro: z.string().optional().nullable(),
  municipio: z.string().optional().nullable(),
  codigoMunicipio: z.string().optional().nullable(),
  uf: z.string().optional().nullable(),
  cep: z.string().optional().nullable(),
  pais: z.string().optional().nullable(),
  foto: z.string().optional(),
});
